[[menu.main]]
  name   = "About"
  url    = "/about/"
  weight = 1

[[menu.main]]
  name   = "Tags"      # ←-- add these four lines
  url    = "/tags/"    #    point to the tags index
  weight = 2           #    higher number = appears to the right


baseURL = "https://enchanting-travesseiro-7ea685.netlify.app/"
languageCode = "en-us"
title = "Tracey Strategy + Execution"
theme = "papermod"

[taxonomies]
  tag = "tags" 

[params]
author = "Tracey Lande"
description = "Strategic execution insights for CEOs and thier leadershp teams."
  ShowBreadCrumbs      = false
  ShowPostNavLinks     = false
  ShowCodeCopyButtons  = false
  ShowShareButtons     = false
  ShowReadingTime      = false
  Toc                  = false
  hideSummary          = true      # list page shows titles only
  hideDescriptionInList = true
[params]
  ShowBreadCrumbs      = false
  ShowPostNavLinks     = false
  ShowCodeCopyButtons  = false
  ShowShareButtons     = false
  ShowReadingTime      = false
  Toc                  = false
  hideSummary          = true      # list page shows titles only
  hideDescriptionInList = true
  author      = "Tracey Lande"
  description = "Strategic marketing insights for high-growth leaders."
ShowReadingTime = true
[[menu.main]]
  name   = "About"
  url    = "/about/"
  weight = 1

